kony = kony || {};
kony.sdk = kony.sdk || {};
kony.sdk.mvvm = kony.sdk.mvvm || {};
kony.sdk.mvvm.v2 = kony.sdk.mvvm.v2 || {};
kony.sdk.mvvm.initApplicationForms = function(appContext) {
    try {
        var frmContactDetailsKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmContactDetailsKAConfig);
        var frmContactDetailsKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmContactDetailsKAController", appContext, frmContactDetailsKAModelConfigObj);
        var frmContactDetailsKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmContactDetailsKAControllerExtension", frmContactDetailsKAControllerObj);
        frmContactDetailsKAControllerObj.setControllerExtensionObject(frmContactDetailsKAstrategyObj);
        var frmContactDetailsKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmContactDetailsKAFormModel", frmContactDetailsKAControllerObj);
        var frmContactDetailsKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmContactDetailsKAFormModelExtension", frmContactDetailsKAFormModelObj);
        frmContactDetailsKAFormModelObj.setFormModelExtensionObj(frmContactDetailsKAFormModelExtObj);
        appContext.setFormController("frmContactDetailsKA", frmContactDetailsKAControllerObj);
        var frmDescriptionDetailsKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmDescriptionDetailsKAConfig);
        var frmDescriptionDetailsKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmDescriptionDetailsKAController", appContext, frmDescriptionDetailsKAModelConfigObj);
        var frmDescriptionDetailsKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmDescriptionDetailsKAControllerExtension", frmDescriptionDetailsKAControllerObj);
        frmDescriptionDetailsKAControllerObj.setControllerExtensionObject(frmDescriptionDetailsKAstrategyObj);
        var frmDescriptionDetailsKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmDescriptionDetailsKAFormModel", frmDescriptionDetailsKAControllerObj);
        var frmDescriptionDetailsKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmDescriptionDetailsKAFormModelExtension", frmDescriptionDetailsKAFormModelObj);
        frmDescriptionDetailsKAFormModelObj.setFormModelExtensionObj(frmDescriptionDetailsKAFormModelExtObj);
        appContext.setFormController("frmDescriptionDetailsKA", frmDescriptionDetailsKAControllerObj);
        var frmDirectionsKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmDirectionsKAConfig);
        var frmDirectionsKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmDirectionsKAController", appContext, frmDirectionsKAModelConfigObj);
        var frmDirectionsKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmDirectionsKAControllerExtension", frmDirectionsKAControllerObj);
        frmDirectionsKAControllerObj.setControllerExtensionObject(frmDirectionsKAstrategyObj);
        var frmDirectionsKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmDirectionsKAFormModel", frmDirectionsKAControllerObj);
        var frmDirectionsKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmDirectionsKAFormModelExtension", frmDirectionsKAFormModelObj);
        frmDirectionsKAFormModelObj.setFormModelExtensionObj(frmDirectionsKAFormModelExtObj);
        appContext.setFormController("frmDirectionsKA", frmDirectionsKAControllerObj);
        var frmOrderDetailsKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmOrderDetailsKAConfig);
        var frmOrderDetailsKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmOrderDetailsKAController", appContext, frmOrderDetailsKAModelConfigObj);
        var frmOrderDetailsKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmOrderDetailsKAControllerExtension", frmOrderDetailsKAControllerObj);
        frmOrderDetailsKAControllerObj.setControllerExtensionObject(frmOrderDetailsKAstrategyObj);
        var frmOrderDetailsKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmOrderDetailsKAFormModel", frmOrderDetailsKAControllerObj);
        var frmOrderDetailsKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmOrderDetailsKAFormModelExtension", frmOrderDetailsKAFormModelObj);
        frmOrderDetailsKAFormModelObj.setFormModelExtensionObj(frmOrderDetailsKAFormModelExtObj);
        appContext.setFormController("frmOrderDetailsKA", frmOrderDetailsKAControllerObj);
        var frmOrderHistoryKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmOrderHistoryKAConfig);
        var frmOrderHistoryKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmOrderHistoryKAController", appContext, frmOrderHistoryKAModelConfigObj);
        var frmOrderHistoryKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmOrderHistoryKAControllerExtension", frmOrderHistoryKAControllerObj);
        frmOrderHistoryKAControllerObj.setControllerExtensionObject(frmOrderHistoryKAstrategyObj);
        var frmOrderHistoryKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmOrderHistoryKAFormModel", frmOrderHistoryKAControllerObj);
        var frmOrderHistoryKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmOrderHistoryKAFormModelExtension", frmOrderHistoryKAFormModelObj);
        frmOrderHistoryKAFormModelObj.setFormModelExtensionObj(frmOrderHistoryKAFormModelExtObj);
        appContext.setFormController("frmOrderHistoryKA", frmOrderHistoryKAControllerObj);
        var frmOrderExecutionKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmOrderExecutionKAConfig);
        var frmOrderExecutionKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmOrderExecutionKAController", appContext, frmOrderExecutionKAModelConfigObj);
        var frmOrderExecutionKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmOrderExecutionKAControllerExtension", frmOrderExecutionKAControllerObj);
        frmOrderExecutionKAControllerObj.setControllerExtensionObject(frmOrderExecutionKAstrategyObj);
        var frmOrderExecutionKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmOrderExecutionKAFormModel", frmOrderExecutionKAControllerObj);
        var frmOrderExecutionKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmOrderExecutionKAFormModelExtension", frmOrderExecutionKAFormModelObj);
        frmOrderExecutionKAFormModelObj.setFormModelExtensionObj(frmOrderExecutionKAFormModelExtObj);
        appContext.setFormController("frmOrderExecutionKA", frmOrderExecutionKAControllerObj);
        var frmOrderListKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmOrderListKAConfig);
        var frmOrderListKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmOrderListKAController", appContext, frmOrderListKAModelConfigObj);
        var frmOrderListKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmOrderListKAControllerExtension", frmOrderListKAControllerObj);
        frmOrderListKAControllerObj.setControllerExtensionObject(frmOrderListKAstrategyObj);
        var frmOrderListKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmOrderListKAFormModel", frmOrderListKAControllerObj);
        var frmOrderListKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmOrderListKAFormModelExtension", frmOrderListKAFormModelObj);
        frmOrderListKAFormModelObj.setFormModelExtensionObj(frmOrderListKAFormModelExtObj);
        appContext.setFormController("frmOrderListKA", frmOrderListKAControllerObj);
        var frmOrderResourceDetailsKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmOrderResourceDetailsKAConfig);
        var frmOrderResourceDetailsKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmOrderResourceDetailsKAController", appContext, frmOrderResourceDetailsKAModelConfigObj);
        var frmOrderResourceDetailsKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmOrderResourceDetailsKAControllerExtension", frmOrderResourceDetailsKAControllerObj);
        frmOrderResourceDetailsKAControllerObj.setControllerExtensionObject(frmOrderResourceDetailsKAstrategyObj);
        var frmOrderResourceDetailsKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmOrderResourceDetailsKAFormModel", frmOrderResourceDetailsKAControllerObj);
        var frmOrderResourceDetailsKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmOrderResourceDetailsKAFormModelExtension", frmOrderResourceDetailsKAFormModelObj);
        frmOrderResourceDetailsKAFormModelObj.setFormModelExtensionObj(frmOrderResourceDetailsKAFormModelExtObj);
        appContext.setFormController("frmOrderResourceDetailsKA", frmOrderResourceDetailsKAControllerObj);
        var frmOrderResourcesListKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmOrderResourcesListKAConfig);
        var frmOrderResourcesListKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmOrderResourcesListKAController", appContext, frmOrderResourcesListKAModelConfigObj);
        var frmOrderResourcesListKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmOrderResourcesListKAControllerExtension", frmOrderResourcesListKAControllerObj);
        frmOrderResourcesListKAControllerObj.setControllerExtensionObject(frmOrderResourcesListKAstrategyObj);
        var frmOrderResourcesListKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmOrderResourcesListKAFormModel", frmOrderResourcesListKAControllerObj);
        var frmOrderResourcesListKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmOrderResourcesListKAFormModelExtension", frmOrderResourcesListKAFormModelObj);
        frmOrderResourcesListKAFormModelObj.setFormModelExtensionObj(frmOrderResourcesListKAFormModelExtObj);
        appContext.setFormController("frmOrderResourcesListKA", frmOrderResourcesListKAControllerObj);
        var frmOrdersViewsKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmOrdersViewsKAConfig);
        var frmOrdersViewsKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmOrdersViewsKAController", appContext, frmOrdersViewsKAModelConfigObj);
        var frmOrdersViewsKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmOrdersViewsKAControllerExtension", frmOrdersViewsKAControllerObj);
        frmOrdersViewsKAControllerObj.setControllerExtensionObject(frmOrdersViewsKAstrategyObj);
        var frmOrdersViewsKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmOrdersViewsKAFormModel", frmOrdersViewsKAControllerObj);
        var frmOrdersViewsKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmOrdersViewsKAFormModelExtension", frmOrdersViewsKAFormModelObj);
        frmOrdersViewsKAFormModelObj.setFormModelExtensionObj(frmOrdersViewsKAFormModelExtObj);
        appContext.setFormController("frmOrdersViewsKA", frmOrdersViewsKAControllerObj);
        var frmResourceExecutionKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmResourceExecutionKAConfig);
        var frmResourceExecutionKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmResourceExecutionKAController", appContext, frmResourceExecutionKAModelConfigObj);
        var frmResourceExecutionKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmResourceExecutionKAControllerExtension", frmResourceExecutionKAControllerObj);
        frmResourceExecutionKAControllerObj.setControllerExtensionObject(frmResourceExecutionKAstrategyObj);
        var frmResourceExecutionKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmResourceExecutionKAFormModel", frmResourceExecutionKAControllerObj);
        var frmResourceExecutionKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmResourceExecutionKAFormModelExtension", frmResourceExecutionKAFormModelObj);
        frmResourceExecutionKAFormModelObj.setFormModelExtensionObj(frmResourceExecutionKAFormModelExtObj);
        appContext.setFormController("frmResourceExecutionKA", frmResourceExecutionKAControllerObj);
        var frmTaskDetailsKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmTaskDetailsKAConfig);
        var frmTaskDetailsKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmTaskDetailsKAController", appContext, frmTaskDetailsKAModelConfigObj);
        var frmTaskDetailsKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmTaskDetailsKAControllerExtension", frmTaskDetailsKAControllerObj);
        frmTaskDetailsKAControllerObj.setControllerExtensionObject(frmTaskDetailsKAstrategyObj);
        var frmTaskDetailsKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmTaskDetailsKAFormModel", frmTaskDetailsKAControllerObj);
        var frmTaskDetailsKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmTaskDetailsKAFormModelExtension", frmTaskDetailsKAFormModelObj);
        frmTaskDetailsKAFormModelObj.setFormModelExtensionObj(frmTaskDetailsKAFormModelExtObj);
        appContext.setFormController("frmTaskDetailsKA", frmTaskDetailsKAControllerObj);
        var frmTaskExecutionKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmTaskExecutionKAConfig);
        var frmTaskExecutionKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmTaskExecutionKAController", appContext, frmTaskExecutionKAModelConfigObj);
        var frmTaskExecutionKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmTaskExecutionKAControllerExtension", frmTaskExecutionKAControllerObj);
        frmTaskExecutionKAControllerObj.setControllerExtensionObject(frmTaskExecutionKAstrategyObj);
        var frmTaskExecutionKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmTaskExecutionKAFormModel", frmTaskExecutionKAControllerObj);
        var frmTaskExecutionKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmTaskExecutionKAFormModelExtension", frmTaskExecutionKAFormModelObj);
        frmTaskExecutionKAFormModelObj.setFormModelExtensionObj(frmTaskExecutionKAFormModelExtObj);
        appContext.setFormController("frmTaskExecutionKA", frmTaskExecutionKAControllerObj);
        var frmTaskResourcesListKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmTaskResourcesListKAConfig);
        var frmTaskResourcesListKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmTaskResourcesListKAController", appContext, frmTaskResourcesListKAModelConfigObj);
        var frmTaskResourcesListKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmTaskResourcesListKAControllerExtension", frmTaskResourcesListKAControllerObj);
        frmTaskResourcesListKAControllerObj.setControllerExtensionObject(frmTaskResourcesListKAstrategyObj);
        var frmTaskResourcesListKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmTaskResourcesListKAFormModel", frmTaskResourcesListKAControllerObj);
        var frmTaskResourcesListKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmTaskResourcesListKAFormModelExtension", frmTaskResourcesListKAFormModelObj);
        frmTaskResourcesListKAFormModelObj.setFormModelExtensionObj(frmTaskResourcesListKAFormModelExtObj);
        appContext.setFormController("frmTaskResourcesListKA", frmTaskResourcesListKAControllerObj);
        var frmStatusFilterKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmStatusFilterKAConfig);
        var frmStatusFilterKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmStatusFilterKAController", appContext, frmStatusFilterKAModelConfigObj);
        var frmStatusFilterKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmStatusFilterKAControllerExtension", frmStatusFilterKAControllerObj);
        frmStatusFilterKAControllerObj.setControllerExtensionObject(frmStatusFilterKAstrategyObj);
        var frmStatusFilterKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmStatusFilterKAFormModel", frmStatusFilterKAControllerObj);
        var frmStatusFilterKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmStatusFilterKAFormModelExtension", frmStatusFilterKAFormModelObj);
        frmStatusFilterKAFormModelObj.setFormModelExtensionObj(frmStatusFilterKAFormModelExtObj);
        appContext.setFormController("frmStatusFilterKA", frmStatusFilterKAControllerObj);
        var frmDateFilterKAModelConfigObj = appContext.getFactorySharedInstance().createConfigClassObject(frmDateFilterKAConfig);
        var frmDateFilterKAControllerObj = appContext.getFactorySharedInstance().createFormControllerObject("kony.sdk.mvvm.frmDateFilterKAController", appContext, frmDateFilterKAModelConfigObj);
        var frmDateFilterKAstrategyObj = appContext.getFactorySharedInstance().createFormControllerExtObject("kony.sdk.mvvm.frmDateFilterKAControllerExtension", frmDateFilterKAControllerObj);
        frmDateFilterKAControllerObj.setControllerExtensionObject(frmDateFilterKAstrategyObj);
        var frmDateFilterKAFormModelObj = appContext.getFactorySharedInstance().createFormModelObject("kony.sdk.mvvm.frmDateFilterKAFormModel", frmDateFilterKAControllerObj);
        var frmDateFilterKAFormModelExtObj = appContext.getFactorySharedInstance().createFormModelExtObject("kony.sdk.mvvm.frmDateFilterKAFormModelExtension", frmDateFilterKAFormModelObj);
        frmDateFilterKAFormModelObj.setFormModelExtensionObj(frmDateFilterKAFormModelExtObj);
        appContext.setFormController("frmDateFilterKA", frmDateFilterKAControllerObj);
    } catch (err) {
        var exception = appContext.getFactorySharedInstance().createExceptionObject(kony.sdk.mvvm.ExceptionCode.CD_ERROR_APP_INIT_FORMS, kony.sdk.mvvm.ExceptionCode.MSG_ERROR_APP_INIT_FORMS, err);
        kony.sdk.mvvm.log.error(exception.toString());
        throw exception;
    }
};