kony = kony || {};
kony.vapps = kony.vapps || {};
kony.vapps.appmenu = kony.vapps.appmenu || {};
kony.vapps.appmenu.widgetconfig = {
    flexScrollContainer: {
        android: {
            "id": "flexScroll",
            "top": "0dp",
            "left": "0dp",
            "width": "80%",
            "height": "100%",
            "zIndex": 1,
            "isVisible": true,
            "clipBounds": true,
            "Location": "[0,0]",
            "layoutType": kony.flex.FLOW_VERTICAL,
            "padding": [0, 0, 0, 0],
            "containerWeight": 100,
            "hExpand": true,
            "vExpand": false,
            "enableScrolling": true,
            "scrollDirection": kony.flex.SCROLL_VERTICAL,
            "horizontalScrollIndicator": false,
            "verticalScrollIndicator": true,
            "skin": "",
            "focusSkin": "",
            "bounces": false,
            "allowHorizontalBounce": false,
            "allowVerticalBounce": false,
            "onSwipe": null
        },
        iphone: {
            "id": "flexScroll",
            "top": "0dp",
            "left": "0dp",
            "width": "80%",
            "height": "100%",
            "zIndex": 1,
            "isVisible": true,
            "clipBounds": true,
            "Location": "[0,0]",
            "layoutType": kony.flex.FLOW_VERTICAL,
            "padding": [0, 0, 0, 0],
            "containerWeight": 100,
            "hExpand": true,
            "vExpand": false,
            "enableScrolling": true,
            "scrollDirection": kony.flex.SCROLL_VERTICAL,
            "horizontalScrollIndicator": false,
            "verticalScrollIndicator": true,
            "skin": "",
            "focusSkin": "",
            "allowHorizontalBounce": false,
            "allowVerticalBounce": false,
            "onSwipe": null
        },
        ipad: {
            "id": "flexScroll",
            "top": "0dp",
            "left": "0dp",
            "width": "33%",
            "height": "100%",
            "zIndex": 1,
            "isVisible": true,
            "clipBounds": true,
            "Location": "[0,0]",
            "layoutType": kony.flex.FLOW_VERTICAL,
            "padding": [0, 0, 0, 0],
            "containerWeight": 100,
            "hExpand": true,
            "vExpand": false,
            "enableScrolling": true,
            "scrollDirection": kony.flex.SCROLL_VERTICAL,
            "horizontalScrollIndicator": false,
            "verticalScrollIndicator": true,
            "skin": "",
            "focusSkin": "",
            "allowHorizontalBounce": false,
            "allowVerticalBounce": false,
            "onSwipe": null
        },
        tabrcandroid: {
            "id": "flexScroll",
            "top": "0dp",
            "left": "0dp",
            "width": "33%",
            "height": "100%",
            "zIndex": 1,
            "isVisible": true,
            "clipBounds": true,
            "Location": "[0,0]",
            "layoutType": kony.flex.FLOW_VERTICAL,
            "padding": [0, 0, 0, 0],
            "containerWeight": 100,
            "hExpand": true,
            "vExpand": false,
            "enableScrolling": true,
            "scrollDirection": kony.flex.SCROLL_VERTICAL,
            "horizontalScrollIndicator": false,
            "verticalScrollIndicator": true,
            "skin": "",
            "focusSkin": "",
            "bounces": false,
            "allowHorizontalBounce": false,
            "allowVerticalBounce": false,
            "onSwipe": null
        }
    },
    flexContainer: {
        android: {
            "id": "flex",
            "top": "0dp",
            "left": "0dp",
            "width": "80%",
            "height": "100%",
            "zIndex": 1,
            "isVisible": true,
            "clipBounds": true,
            "Location": "[0,0]",
            "layoutType": kony.flex.FLOW_VERTICAL,
            "padding": [0, 0, 0, 0],
            "onClick": null,
            "skin": "",
            "focusSkin": ""
        },
        iphone: {
            "id": "flex",
            "top": "0dp",
            "left": "0dp",
            "width": "80%",
            "height": "100%",
            "zIndex": 1,
            "isVisible": true,
            "clipBounds": true,
            "Location": "[0,0]",
            "layoutType": kony.flex.FLOW_VERTICAL,
            "padding": [0, 0, 0, 0],
            "onClick": "",
            "skin": "",
            "focusSkin": ""
        },
        ipad: {
            "id": "flex",
            "top": "0dp",
            "left": "0dp",
            "width": "33%",
            "height": "100%",
            "zIndex": 1,
            "isVisible": true,
            "clipBounds": true,
            "Location": "[0,0]",
            "layoutType": kony.flex.FLOW_VERTICAL,
            "padding": [0, 0, 0, 0],
            "onClick": "",
            "skin": "",
            "focusSkin": ""
        },
        tabrcandroid: {
            "id": "flex",
            "top": "0dp",
            "left": "0dp",
            "width": "33%",
            "height": "100%",
            "zIndex": 1,
            "isVisible": true,
            "clipBounds": true,
            "Location": "[0,0]",
            "layoutType": kony.flex.FLOW_VERTICAL,
            "padding": [0, 0, 0, 0],
            "onClick": null,
            "skin": "",
            "focusSkin": ""
        }
    },
    button: {
        android: {
            "id": "button",
            "top": "0dp",
            "left": "0dp",
            "width": "60dp",
            "height": "40dp",
            "zIndex": 1,
            "isVisible": true,
            "centerX": "50%",
            "centerY": "50%",
            "text": "",
            "skin": "",
            "focusSkin": "",
            "onClick": null,
            "padding": [0, 0, 0, 0],
            "contentAlignment": constants.CONTENT_ALIGN_CENTER,
            "displayText": true,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 0,
            "glowEffect": false,
            "showProgressIndicator": false
        },
        iphone: {
            "id": "button",
            "top": "0dp",
            "left": "0dp",
            "width": "60dp",
            "height": "40dp",
            "zIndex": 1,
            "isVisible": true,
            "centerX": "50%",
            "centerY": "50%",
            "text": "",
            "skin": "",
            "focusSkin": "",
            "onClick": "",
            "padding": [0, 0, 0, 0],
            "contentAlignment": constants.CONTENT_ALIGN_CENTER,
            "displayText": true,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 0,
            "glowEffect": false,
            "showProgressIndicator": false
        },
        ipad: {
            "id": "button",
            "top": "0dp",
            "left": "0dp",
            "width": "60dp",
            "height": "40dp",
            "zIndex": 1,
            "isVisible": true,
            "centerX": "50%",
            "centerY": "50%",
            "text": "",
            "skin": "",
            "focusSkin": "",
            "onClick": "",
            "padding": [0, 0, 0, 0],
            "contentAlignment": constants.CONTENT_ALIGN_CENTER,
            "displayText": true,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 0,
            "glowEffect": false,
            "showProgressIndicator": false
        },
        tabrcandroid: {
            "id": "button",
            "top": "0dp",
            "left": "0dp",
            "width": "60dp",
            "height": "40dp",
            "zIndex": 1,
            "isVisible": true,
            "centerX": "50%",
            "centerY": "50%",
            "text": "",
            "skin": "",
            "focusSkin": "",
            "onClick": null,
            "padding": [0, 0, 0, 0],
            "contentAlignment": constants.CONTENT_ALIGN_CENTER,
            "displayText": true,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 0,
            "glowEffect": false,
            "showProgressIndicator": false
        }
    },
    image: {
        android: {
            "id": "image",
            "top": "3dp",
            "left": "5dp",
            "width": "50dp",
            "height": "50dp",
            "zIndex": 1,
            "isVisible": true,
            "centerX": "50%",
            "centerY": "50%",
            "src": "",
            "imageWhenFailed": null,
            "imageWhileDownloading": null,
            "padding": [0, 0, 0, 0],
            "imageScaleMode": constants.IMAGE_SCALE_MODE_MAINTAIN_ASPECT_RATIO,
            "referenceWidth": null,
            "referenceHeight": null,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 6
        },
        iphone: {
            "id": "image",
            "top": "3dp",
            "left": "5dp",
            "width": "50dp",
            "height": "50dp",
            "zIndex": 1,
            "isVisible": true,
            "centerX": "50%",
            "centerY": "50%",
            "src": "",
            "imageWhenFailed": null,
            "imageWhileDownloading": null,
            "padding": [0, 0, 0, 0],
            "imageScaleMode": constants.IMAGE_SCALE_MODE_MAINTAIN_ASPECT_RATIO,
            "referenceWidth": null,
            "referenceHeight": null,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 6
        },
        ipad: {
            "id": "image",
            "top": "3dp",
            "left": "5dp",
            "width": "50dp",
            "height": "50dp",
            "zIndex": 1,
            "isVisible": true,
            "centerX": "50%",
            "centerY": "50%",
            "src": "",
            "imageWhenFailed": null,
            "imageWhileDownloading": null,
            "padding": [0, 0, 0, 0],
            "imageScaleMode": constants.IMAGE_SCALE_MODE_MAINTAIN_ASPECT_RATIO,
            "referenceWidth": null,
            "referenceHeight": null,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 6
        },
        tabrcandroid: {
            "id": "image",
            "top": "3dp",
            "left": "5dp",
            "width": "50dp",
            "height": "50dp",
            "zIndex": 1,
            "isVisible": true,
            "centerX": "50%",
            "centerY": "50%",
            "src": "",
            "imageWhenFailed": null,
            "imageWhileDownloading": null,
            "padding": [0, 0, 0, 0],
            "imageScaleMode": constants.IMAGE_SCALE_MODE_MAINTAIN_ASPECT_RATIO,
            "referenceWidth": null,
            "referenceHeight": null,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 6
        }
    },
    label: {
        android: {
            "id": "label",
            "top": "3dp",
            "left": "20dp",
            "width": "130dp",
            "height": "50dp",
            "zIndex": 1,
            "isVisible": true,
            "text": "defaultText",
            "skin": "",
            "padding": [0, 0, 0, 0],
            "contentAlignment": constants.CONTENT_ALIGN_MIDDLE_LEFT,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 6,
            "textCopyable": false
        },
        iphone: {
            "id": "label",
            "top": "3dp",
            "left": "20dp",
            "width": "130dp",
            "height": "50dp",
            "zIndex": 1,
            "isVisible": true,
            "text": "defaultText",
            "skin": "",
            "padding": [0, 0, 0, 0],
            "contentAlignment": constants.CONTENT_ALIGN_MIDDLE_LEFT,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 6,
            "textCopyable": false
        },
        ipad: {
            "id": "label",
            "top": "3dp",
            "left": "20dp",
            "width": "130dp",
            "height": "50dp",
            "zIndex": 1,
            "isVisible": true,
            "text": "defaultText",
            "skin": "",
            "padding": [0, 0, 0, 0],
            "contentAlignment": constants.CONTENT_ALIGN_MIDDLE_LEFT,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 6,
            "textCopyable": false
        },
        tabrcandroid: {
            "id": "label",
            "top": "3dp",
            "left": "20dp",
            "width": "130dp",
            "height": "50dp",
            "zIndex": 1,
            "isVisible": true,
            "text": "defaultText",
            "skin": "",
            "padding": [0, 0, 0, 0],
            "contentAlignment": constants.CONTENT_ALIGN_MIDDLE_LEFT,
            "marginInPixel": false,
            "paddingInPixel": false,
            "containerWeight": 6,
            "textCopyable": false
        }
    },
    line: {
        android: {
            "id": "line",
            "top": "0dp",
            "left": "0dp",
            "width": "250dp",
            "height": "1dp",
            "zIndex": 1,
            "isVisible": true,
            "skin": "",
            "thickness": 1,
            "marginInPixel": false,
            "paddingInPixel": false
        },
        iphone: {
            "id": "line",
            "top": "0dp",
            "left": "0dp",
            "width": "250dp",
            "height": "1dp",
            "zIndex": 1,
            "isVisible": true,
            "skin": "",
            "thickness": 1,
            "marginInPixel": false,
            "paddingInPixel": false
        },
        ipad: {},
        tabrcandroid: {}
    },
    getWidgetConfig: function(widgetType) {
        //kony.print("efgh");
        var platFormName = kony.sdk.mvvm.Utils.getPlatformName();
        //var platFormName = "iphone";
        kony.print("atul platFormName : " + platFormName)
        var config = kony.vapps.appmenu.widgetconfig[widgetType][platFormName];
        kony.print("atul config : " + config);
        return config;
    }
};