//Type your code here
var frmOrderAssetKAConfig={
  "formid":"frmOrderAssetKA",
  "frmOrderAssetKA":{
    "entity":"OrderObject",
    "objectServiceOptions":{
      "access":"offline"
    },
    "objectServiceName":"OrderExecution",
    "additionalFields":["OrderObject.WarrantExpirationDate","OrderObject.Code","OrderObject.FunctionalLocation_id","OrderObject.FunctionalLocationType_id","OrderObject.ObjectType"],
    "query":"select oo.Description,oo.ObjectType,oo.WarrantStartDate,oo.WarrantExpirationDate,oo.Manufacturer,oo.ManufactureDate,oo.FunctionalLocation_id,oo.Code,oo.InstallationDate,oo.SerialNumber,oo.Plant_id,oo.Material_id,oo.IsLeaf,oo.FunctionalLocationType_id,m.Description as CompDescription,mt.Name from OrderObject oo left join Material m on oo.Material_id = m.id left join MaterialType mt on m.Type_id = mt.id  where oo.WorkOrder_id='{x}'",
    "querytype":"sql"
  },
  "lblObjectNameValueKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"Description"
    }
  },
  "lblObjectCategoryValueKA":{
    "fieldprops":{
      "entity":"MaterialType",
      "widgettype":"Label",
      "field":"Name"
    }
  },
  "lblObjectWarrantyValueKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"WarrantStartDate"
    }
  },
  "lblObjectManufacturerValueKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"Manufacturer"
    }
  },
  "lblObjectManufacturedDateValueKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"ManufactureDate"
    }
  },
  "lblObjectStartUpDateValueKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"InstallationDate"
    }
  },
  "lblObjectSerialNumberValueKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"SerialNumber"
    }
  },
  "lblObjectMaintenancePlanValueKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"Plant_id"
    }
  },
  "lblObjectProductNumberValueKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"Material_id"
    }
  },
  "lblCompValueKA":{
    "fieldprops":{
      "entity":"Material",
      "widgettype":"Label",
      "field":"CompDescription"
    }
  },
  "lblCompNameValueKA":{
    "fieldprops":{
      "entity":"MaterialType",
      "widgettype":"Label",
      "field":"Name"
    }
  },
  "imgIsBomKA":{
    "fieldprops":{
      "entity":"OrderObject",
      "widgettype":"Label",
      "field":"IsLeaf"
    }
  }
};